#!/usr/bin/env python3
"""Generate asvs-5.0-coverage.md from asvs-5.0-map.json and the released ASVS 5.0 data.

Fetches the standard from its GitHub release, verifies the checksum recorded in the map,
asserts that every ASVS id cited in the map actually exists, and writes the coverage table.
Re-run when ASVS publishes a new version; a stale mapping is a false claim.

    python3 mapping/build-coverage.py
"""
import hashlib
import json
import pathlib
import sys
import urllib.request
from collections import OrderedDict, defaultdict

HERE = pathlib.Path(__file__).parent
MAP = json.loads((HERE / "asvs-5.0-map.json").read_text())
CACHE = HERE / ".asvs-cache.json"
URL = (
    "https://github.com/OWASP/ASVS/releases/download/"
    f"{MAP['asvs_release']}/OWASP_Application_Security_Verification_Standard_"
    f"{MAP['asvs_version']}_en.flat.json"
)
TIERS = {
    1: ("Tier 1", "PR gate - static, no running app"),
    2: ("Tier 2", "Post-deploy probe - needs a deployed URL"),
    3: ("Tier 3", "Test-suite contract - the consuming project writes it"),
    4: ("Tier 4", "Attested manual - the control is the date"),
}


def load_asvs() -> list:
    if CACHE.exists():
        raw = CACHE.read_bytes()
    else:
        print(f"fetching {URL}", file=sys.stderr)
        raw = urllib.request.urlopen(URL, timeout=60).read()
        CACHE.write_bytes(raw)
    digest = hashlib.sha256(raw).hexdigest()
    if digest != MAP["asvs_sha256"]:
        sys.exit(
            f"FAIL checksum mismatch\n  expected {MAP['asvs_sha256']}\n  got      {digest}\n"
            "The standard changed. Re-review the mapping before updating the recorded hash."
        )
    return json.loads(raw)["requirements"]


def main() -> None:
    reqs = load_asvs()
    n_controls = len(MAP["controls"])
    by_id = {r["req_id"]: r for r in reqs}

    chapters = OrderedDict()
    for r in reqs:
        chapters.setdefault(r["chapter_id"], {"name": r["chapter_name"], "reqs": []})
        chapters[r["chapter_id"]]["reqs"].append(r["req_id"])

    # Every cited id must exist in the standard. A typo here is a fabricated citation.
    cited, unknown = set(), []
    for c in MAP["controls"]:
        for rid in c["asvs"]:
            cited.add(rid)
            if rid not in by_id:
                unknown.append((c["id"], rid))
    if unknown:
        for cid, rid in unknown:
            print(f"FAIL control {cid} cites {rid}, which is not in ASVS {MAP['asvs_version']}",
                  file=sys.stderr)
        sys.exit(1)

    touched_by_chapter = defaultdict(set)
    for rid in cited:
        touched_by_chapter[by_id[rid]["chapter_id"]].add(rid)

    controls_by_chapter = defaultdict(set)
    for c in MAP["controls"]:
        for rid in c["asvs"]:
            controls_by_chapter[by_id[rid]["chapter_id"]].add(c["id"])

    out = []
    w = out.append
    w("# ASVS 5.0 coverage mapping\n")
    w(f"Generated by `mapping/build-coverage.py` from `mapping/asvs-5.0-map.json` against "
      f"[OWASP ASVS {MAP['asvs_version']}]"
      f"(https://github.com/OWASP/ASVS/releases/tag/{MAP['asvs_release']}) "
      f"(`sha256:{MAP['asvs_sha256'][:16]}...`).\n")
    w("**Do not edit this file by hand.** Edit the map and regenerate.\n")

    w("## What this mapping does and does not claim\n")
    w("It claims: each control below was read against the ASVS requirements listed beside it, "
      "and those requirement ids exist in the released standard (the generator fails if one "
      "does not).\n")
    w("It does **not** claim ASVS compliance, alignment, or equivalence at any assurance level. "
      "A control that 'maps to' a requirement often covers part of it, occasionally states it "
      "more concretely, and sometimes is simply adjacent. Where ASVS is better, the note says "
      "so.\n")

    total = len(reqs)
    w(f"**Headline: {len(cited)} of {total} ASVS {MAP['asvs_version']} requirements "
      f"({len(cited) * 100 // total}%) are touched by at least one of the {n_controls} "
      "controls.** "
      f"The other {total - len(cited)} ({(total - len(cited)) * 100 // total}%) are not, "
      "and the chapter table below says where.\n")

    w("## Coverage by ASVS chapter\n")
    w("| Chapter | Reqs | Touched | % | Controls | Assessment |")
    w("| --- | ---: | ---: | ---: | --- | --- |")
    ASSESS = {
        "V1": "Injection and encoding core is covered; the long tail (LDAP, XPath, LaTeX, ReDoS, CSV formula injection, memory safety) is not.",
        "V2": "Input validation covered. Business-logic requirements (step order, transactions, resource locking, multi-user approval) are not.",
        "V3": "Cookies, headers and CSRF covered. Not covered: DOM clobbering, postMessage, XSSI/JSONP, subresource integrity, redirect handling.",
        "V4": "Thin. HTTP request smuggling (V4.2) and WebSocket security (V4.4) are entirely absent from the controls.",
        "V5": "Upload basics covered. Archive handling (zip bombs, symlinks, zip slip) and pixel-flood limits are not.",
        "V6": "**Weakest area.** 47 requirements on authentication; the controls address password storage, brute-force and enumeration only. MFA, recovery flows and password policy detail are absent.",
        "V7": "Session creation and termination covered. Inactivity and absolute timeouts, concurrent-session policy and step-up re-auth are not.",
        "V8": "Strongest area. Function, data and field-level authorization plus multi-tenancy all map directly.",
        "V9": "Near-complete. Control 13 covers self-contained token validation thoroughly.",
        "V10": "**Largest single gap by count.** 36 OAuth/OIDC requirements against one control. Anything doing real OAuth work must read V10 directly.",
        "V11": "Password hashing and cipher choice covered. Key lifecycle, crypto agility, constant-time operations and nonce reuse are not.",
        "V12": "TLS for public traffic covered. mTLS, internal service-to-service TLS and certificate validation are not.",
        "V13": "Well covered. V13.4 (unintended surface) is the single best-matched section in the standard.",
        "V14": "Classification and minimisation covered. Retention schedules, caching controls and file-metadata stripping are not.",
        "V15": "Well covered - dependency management, mass assignment and field trimming all map directly. Concurrency (V15.4) does not.",
        "V16": "Well covered. Audit trail and log hygiene map directly; log format and time-source requirements do not.",
        "V17": "**Zero coverage, by design.** WebRTC is out of scope for these controls entirely.",
    }
    for cid, ch in chapters.items():
        n, t = len(ch["reqs"]), len(touched_by_chapter[cid])
        ctrls = sorted(controls_by_chapter[cid])
        cs = ", ".join(str(x) for x in ctrls) if ctrls else "—"
        w(f"| {cid} {ch['name']} | {n} | {t} | {t * 100 // n}% | {cs} | {ASSESS.get(cid, '')} |")
    w(f"| **Total** | **{total}** | **{len(cited)}** | **{len(cited) * 100 // total}%** | | |")
    w("")

    w("## Control-by-control map\n")
    w("Tiers describe how a control can be checked, not how important it is:\n")
    for k in sorted(TIERS):
        w(f"- **{TIERS[k][0]}** — {TIERS[k][1]}")
    w("")
    cur = None
    for c in MAP["controls"]:
        if c["group"] != cur:
            cur = c["group"]
            w(f"\n### Group {cur}\n")
            w("| # | Control | Tier | ASVS 5.0 | Note |")
            w("| ---: | --- | :---: | --- | --- |")
        ids = ", ".join(f"`{i}`" for i in c["asvs"]) if c["asvs"] else "**none**"
        w(f"| {c['id']} | {c['title']} | {c['tier']} | {ids} | {c['note']} |")
    w("")

    w("## Controls with no ASVS counterpart\n")
    for c in MAP["controls"]:
        if not c["asvs"]:
            w(f"- **{c['id']}. {c['title']}** — {c['note']}")
    w("")

    w("## Automation feasibility\n")
    tier_counts = defaultdict(list)
    for c in MAP["controls"]:
        tier_counts[c["tier"]].append(c["id"])
    w("| Tier | What it means | Controls | Count |")
    w("| :---: | --- | --- | ---: |")
    for k in sorted(TIERS):
        ids = tier_counts[k]
        w(f"| {k} | {TIERS[k][1]} | {', '.join(str(i) for i in ids)} | {len(ids)} |")
    auto = len(tier_counts[1]) + len(tier_counts[2])
    w("")
    w(f"**{auto} of {n_controls} controls ({auto * 100 // n_controls}%) can be checked by CI "
      f"this repository can ship.** The remaining {n_controls - auto} are a contract with the "
      "consuming project "
      "(Tier 3) or an action someone takes and dates (Tier 4). Automating the automatable "
      "subset and being explicit about the rest is the honest position; a green pipeline is "
      "evidence about Tiers 1 and 2 and nothing else.\n")

    (HERE / "asvs-5.0-coverage.md").write_text("\n".join(out))
    print(f"wrote asvs-5.0-coverage.md  ({len(cited)}/{total} reqs touched, "
          f"{len(out)} lines, all {len(cited)} cited ids validated)")


if __name__ == "__main__":
    main()
